<a href="https://colab.research.google.com/github/Forrward/LABbl/blob/main/lab1/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [3]:
import pandas as pd

In [17]:
df = pd.read_csv("world-data-2023.csv")
df

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [ ]:
#Колонки датасета
df.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

In [ ]:
#Первые 5 значений
df.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887

In [ ]:
#Последние 5 значений
df.tail()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [ ]:
#Статистику по числовым колонкам
df.describe(include="all")

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
count,195,195,188,188,194,171,189.000000,194.000000,192,188,...,188,188.000000,194,176,169,183,176,190,194.000000,194.000000
unique,195,137,188,168,194,105,NaN,NaN,192,184,...,160,NaN,194,145,119,156,164,190,NaN,NaN
top,Afghanistan,25,AF,17.40%,"652,230","2,000",NaN,NaN,Kabul,143,...,40.50%,NaN,"38,041,754",68.80%,19.50%,36.60%,4.59%,"9,797,273",NaN,NaN
freq,1,7,1,3,1,7,NaN,NaN,1,2,...,3,NaN,1,3,4,4,3,1,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,20.214974,360.546392,NaN,NaN,...,NaN,1.839840,NaN,NaN,NaN,NaN,NaN,NaN,19.092351,20.232434
std,NaN,NaN,NaN,NaN,NaN,NaN,9.945774,323.236419,NaN,NaN,...,NaN,1.684261,NaN,NaN,NaN,NaN,NaN,NaN,23.961779,66.716110
min,NaN,NaN,NaN,NaN,NaN,NaN,5.900000,1.000000,NaN,NaN,...,NaN,0.010000,NaN,NaN,NaN,NaN,NaN,NaN,-40.900557,-175.198242
25%,NaN,NaN,NaN,NaN,NaN,NaN,11.300000,82.500000,NaN,NaN,...,NaN,0.332500,NaN,NaN,NaN,NaN,NaN,NaN,4.544175,-7.941496
50%,NaN,NaN,NaN,NaN,NaN,NaN,17.950000,255.500000,NaN,NaN,...,NaN,1.460000,NaN,NaN,NaN,NaN,NaN,NaN,17.273849,20.972652
75%,NaN,NaN,NaN,NaN,NaN,NaN,28.750000,506.750000,NaN,NaN,...,NaN,2.935000,NaN,NaN,NaN,NaN,NaN,NaN,40.124603,48.281523
max,NaN,NaN,NaN,NaN,NaN,NaN,46.080000,1876.000000,NaN,NaN,...,NaN,8.420000,NaN,NaN,NaN,NaN,NaN,NaN,64.963051,178.065032

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета

In [ ]:
#Средние значения
df.mean(numeric_only=True)

Birth Rate                   20.214974
Calling Code                360.546392
Fertility Rate                2.698138
Infant mortality             21.332804
Life expectancy              72.279679
Maternal mortality ratio    160.392265
Physicians per thousand       1.839840
Latitude                     19.092351
Longitude                    20.232434
dtype: float64

In [ ]:
#Минимальные значения
df.min(numeric_only=True)

Birth Rate                    5.900000
Calling Code                  1.000000
Fertility Rate                0.980000
Infant mortality              1.400000
Life expectancy              52.800000
Maternal mortality ratio      2.000000
Physicians per thousand       0.010000
Latitude                    -40.900557
Longitude                  -175.198242
dtype: float64

In [ ]:
df.max(numeric_only=True)

Birth Rate                    46.080000
Calling Code                1876.000000
Fertility Rate                 6.910000
Infant mortality              84.500000
Life expectancy               85.400000
Maternal mortality ratio    1150.000000
Physicians per thousand        8.420000
Latitude                      64.963051
Longitude                    178.065032
dtype: float64

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [23]:
#Вывести типы колонок тут
df.dtypes

Country                                       object
Density\n(P/Km2)                              object
Abbreviation                                  object
Agricultural Land( %)                         object
Land Area(Km2)                                object
Armed Forces size                             object
Birth Rate                                   float64
Calling Code                                 float64
Capital/Major City                            object
Co2-Emissions                                 object
CPI                                           object
CPI Change (%)                                object
Currency-Code                                 object
Fertility Rate                               float64
Forested Area (%)                             object
Gasoline Price                                object
GDP                                           object
Gross primary education enrollment (%)        object
Gross tertiary education enrollment (%)       object
Infant mortality                             float64
Largest city                                  object
Life expectancy                              float64
Maternal mortality ratio                     float64
Minimum wage                                  object
Official language                             object
Out of pocket health expenditure              object
Physicians per thousand                      float64
Population                                    object
Population: Labor force participation (%)     object
Tax revenue (%)                               object
Total tax rate                                object
Unemployment rate                             object
Urban_population                              object
Latitude                                     float64
Longitude                                    float64
dtype: object

In [62]:
df.astype('object')

df['Birth Rate'] = df['Birth Rate'].astype('float64')
df['Calling Code'] = df['Calling Code'].astype('float64')
df['Fertility Rate'] = df['Fertility Rate'].astype('float64')
df['Infant mortality'] = df['Infant mortality'].astype('float64')
df['Life expectancy'] = df['Life expectancy'].astype('float64')
df['Maternal mortality ratio'] = df['Maternal mortality ratio'].astype('float64')
df['Physicians per thousand'] = df['Physicians per thousand'].astype('float64')
df['Latitude'] = df['Latitude'].astype('float64')
df['Longitude'] = df['Longitude'].astype('float64')

df['Country'] = df['Country'].astype('category')
df['Abbreviation'] = df['Abbreviation'].astype('category')
df['Capital/Major City'] = df['Capital/Major City'].astype('category')
df['Currency-Code'] = df['Currency-Code'].astype('category')
df['Largest city'] = df['Largest city'].astype('category')
df['Official language'] = df['Official language'].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    category
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    category
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    category
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    category
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    category
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    category
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          194 non-null    category
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  Latitude                                   194 non-null    float64
 34  Longitude                                  194 non-null    float64
dtypes: category(7), float64(9), object(19)
memory usage: 80.8+ KB

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

Признаки:
1. Категориальные
2. Порядковые
3. Числовые

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [ ]:
#Фильтр колонки 2
df[df['Calling Code']<20]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
5,Antigua and Barbuda,223,AG,20.50%,443,0,15.33,1.0,"St. John's, Saint John",557,...,24.30%,2.76,"97,118",NaN,16.50%,43.00%,NaN,"23,800",17.060816,-61.796428
11,The Bahamas,39,BS,1.40%,"13,880","1,000",13.97,1.0,"Nassau, Bahamas","1,786",...,27.80%,1.94,"389,482",74.60%,14.80%,33.80%,10.36%,"323,784",25.034280,-77.396280
14,Barbados,668,BB,23.30%,430,"1,000",10.65,1.0,Bridgetown,"1,276",...,45.20%,2.48,"287,025",65.20%,27.50%,35.60%,10.33%,"89,431",13.193887,-59.543198
32,Canada,4,CA,6.90%,"9,984,670","72,000",10.10,1.0,Ottawa,"544,894",...,14.60%,2.61,"36,991,981",65.10%,12.80%,24.50%,5.56%,"30,628,482",56.130366,-106.346771
48,Dominica,96,DM,33.30%,751,NaN,12.00,1.0,Roseau,180,...,28.40%,1.08,"71,808",NaN,22.10%,32.60%,NaN,"50,830",15.414999,-61.370976
49,Dominican Republic,225,DO,48.70%,"48,670","71,000",19.51,1.0,Santo Domingo,"25,258",...,43.70%,1.56,"10,738,958",64.30%,13.00%,48.80%,5.84%,"8,787,475",18.735693,-70.162651
67,Grenada,331,GD,23.50%,349,NaN,16.47,1.0,"St. George's, Grenada",268,...,57.00%,1.41,"112,003",NaN,19.40%,47.80%,NaN,"40,765",12.116500,-61.679000
87,Kazakhstan,7,KZ,80.40%,"2,724,900","71,000",21.77,7.0,Astana,"247,207",...,38.80%,3.25,"18,513,930",68.80%,11.70%,28.40%,4.59%,"10,652,915",48.019573,66.923684
143,Russia,9,RU,13.30%,"17,098,240","1,454,000",11.50,7.0,Moscow,"1,732,027",...,36.40%,4.01,"144,373,535",61.80%,11.40%,46.20%,4.59%,"107,683,889",61.524010,105.318756
145,Saint Kitts and Nevis,205,KN,23.10%,261,NaN,12.60,1.0,Basseterre,238,...,56.60%,2.52,"52,823",NaN,18.50%,49.70%,NaN,"16,269",17.357822,-62.782998
146,Saint Lucia,301,LC,17.40%,616,NaN,12.00,1.0,Castries,414,...,48.40%,0.64,"182,790",67.10%,18.20%,34.70%,20.71%,"34,280",13.909444,-60.978893
147,Saint Vincent and the Grenadines,284,VC,25.60%,389,NaN,14.24,1.0,Kingstown,220,...,21.40%,0.66,"100,455",65.90%,25.40%,37.00%,18.88%,"58,185",12.984305,-61.287228
177,Trinidad and Tobago,273,TT,10.50%,"5,128","4,000",12.94,1.0,Port of Spain,"43,868",...,37.30%,4.17,"1,394,973",60.00%,19.50%,40.50%,2.69%,"741,944",10.691803,-61.222503
186,United States,36,US,44.40%,"9,833,517","1,359,000",11.60,1.0,"Washington, D.C.","5,006,302",...,11.10%,2.61,"328,239,523",62.00%,9.60%,36.60%,14.70%,"270,663,028",37.090240,-95.712891

In [ ]:
#Фильтр колонки 2
df[(df['Birth Rate'] > 10) & (df['Birth Rate'] < 11)]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
14,Barbados,668,BB,23.30%,430,"1,000",10.65,1.0,Bridgetown,"1,276",...,45.20%,2.48,"287,025",65.20%,27.50%,35.60%,10.33%,"89,431",13.193887,-59.543198
16,Belgium,383,BE,44.60%,"30,528","32,000",10.30,32.0,City of Brussels,"96,889",...,17.60%,3.07,"11,484,055",53.60%,24.00%,55.40%,5.59%,"11,259,082",50.503887,4.469936
32,Canada,4,CA,6.90%,"9,984,670","72,000",10.10,1.0,Ottawa,"544,894",...,14.60%,2.61,"36,991,981",65.10%,12.80%,24.50%,5.56%,"30,628,482",56.130366,-106.346771
36,China,153,CN,56.20%,"9,596,960","2,695,000",10.90,86.0,Beijing,"9,893,038",...,32.40%,1.98,"1,397,715,000",68.00%,9.40%,59.20%,4.32%,"842,933,962",35.861660,104.195397
42,Cuba,106,CU,59.90%,"110,860","76,000",10.17,53.0,Havana,"28,284",...,NaN,8.42,"11,333,483",53.60%,NaN,NaN,1.64%,"8,739,135",21.521757,-77.781167
43,Cyprus,131,CY,12.20%,"9,251","16,000",10.46,357.0,Nicosia,"6,626",...,43.90%,1.95,"1,198,575",63.10%,24.50%,22.40%,7.27%,"800,708",35.126413,33.429859
44,Czech Republic,139,CZ,45.20%,"78,867","23,000",10.70,420.0,Prague,"102,218",...,14.80%,4.12,"10,669,709",60.60%,14.90%,46.10%,1.93%,"7,887,156",49.817492,15.472962
46,Denmark,137,DK,62.00%,"43,094","15,000",10.60,45.0,Copenhagen,"31,786",...,13.70%,4.01,"5,818,553",62.20%,32.40%,23.80%,4.91%,"5,119,978",56.263920,9.501785
55,Estonia,31,EE,23.10%,"45,228","6,000",10.90,372.0,Tallinn,"16,590",...,22.80%,4.48,"1,331,824",63.60%,20.90%,47.80%,5.11%,"916,024",58.595272,25.013607
100,Luxembourg,242,LU,53.70%,"2,586","2,000",10.30,352.0,Luxembourg City,"8,988",...,10.60%,3.01,"645,397",59.30%,26.50%,20.40%,5.36%,"565,488",49.815273,6.129583
109,Mauritius,626,MU,42.40%,"2,040","3,000",10.20,230.0,Port Louis,"4,349",...,50.70%,2.53,"1,265,711",58.30%,19.10%,22.20%,6.67%,"515,980",-20.348404,57.552152
112,Moldova,123,MD,74.20%,"33,851","7,000",10.10,373.0,Chi����,"5,115",...,46.20%,3.21,"2,657,637",43.10%,17.70%,38.70%,5.47%,"1,135,502",47.411631,28.369885
129,Norway,15,NO,2.70%,"323,802","23,000",10.40,47.0,Oslo,"41,023",...,14.30%,2.92,"5,347,896",63.80%,23.90%,36.20%,3.35%,"4,418,218",60.472024,8.468946
139,Poland,124,PL,46.90%,"312,685","191,000",10.20,48.0,Warsaw,"299,037",...,23.20%,2.38,"37,970,874",56.70%,17.40%,40.80%,3.47%,"22,796,574",51.919438,19.145136
157,Slovakia,114,SK,39.20%,"49,035","16,000",10.60,421.0,Bratislava,"32,424",...,18.40%,3.42,"5,454,073",59.50%,18.70%,49.70%,5.56%,"2,930,419",48.669026,19.699024
173,Thailand,137,TH,43.30%,"513,120","455,000",10.34,66.0,Bangkok,"283,763",...,11.80%,0.81,"69,625,582",67.30%,14.90%,29.50%,0.75%,"35,294,600",15.870032,100.992541
184,United Arab Emirates,118,AE,5.50%,"83,600","63,000",10.33,971.0,Abu Dhabi,"206,324",...,17.80%,2.53,"9,770,529",82.10%,0.10%,15.90%,2.35%,"8,479,744",23.424076,53.847818

In [ ]:
#Фильтр колонки 3
df[df['Physicians per thousand'] == 0.42]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
19,Bhutan,20,BT,13.60%,"38,394","6,000",17.26,975.0,Thimphu,"1,261",...,19.80%,0.42,"727,145",66.70%,16.00%,35.30%,2.34%,"317,538",27.514162,90.433601
107,Marshall Islands,329,MH,63.90%,181,NaN,29.03,692.0,Majuro,143,...,10.00%,0.42,"58,791",NaN,17.80%,65.90%,NaN,"45,514",7.131474,171.184478
119,Namibia,3,NaN,47.10%,"824,292","16,000",28.64,264.0,Windhoek,"4,228",...,8.30%,0.42,"2,494,530",59.50%,27.10%,20.70%,20.27%,"1,273,258",-22.957640,18.490410

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [18]:
#Группировка
df.groupby('Country').mean()

<ipython-input-18-a1dc0ffdd597>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Country').mean()

,Birth Rate,Calling Code,Fertility Rate,Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Latitude,Longitude
Country,,,,,,,,,
Afghanistan,32.49,93.0,4.47,47.9,64.5,638.0,0.28,33.939110,67.709953
Albania,11.78,355.0,1.62,7.8,78.5,15.0,1.20,41.153332,20.168331
Algeria,24.28,213.0,3.02,20.1,76.7,112.0,1.72,28.033886,1.659626
Andorra,7.20,376.0,1.27,2.7,NaN,NaN,3.33,42.506285,1.521801
Angola,40.73,244.0,5.52,51.6,60.8,241.0,0.21,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...
Venezuela,17.88,58.0,2.27,21.4,72.1,125.0,1.92,6.423750,-66.589730
Vietnam,16.75,84.0,2.05,16.5,75.3,43.0,0.82,14.058324,108.277199
Yemen,30.45,967.0,3.79,42.9,66.1,164.0,0.31,15.552727,48.516388
Zambia,36.19,260.0,4.63,40.4,63.5,213.0,1.19,-13.133897,27.849332
Zimbabwe,30.68,263.0,3.62,33.9,61.2,458.0,0.21,-19.015438,29.154857

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация